// react/src/App.tsx
import {useEffect, useState} from 'react'
import './styles.css'
import {createClient} from 'pexels';
import {Image} from "./Image.tsx";

function App() {
  const [count, setCount] = useState(0)
  const [response, setResponse] = useState<any[] | null>(null);
  const client = createClient('eqDK60Xl9lzIP4RHt4YCNdwO2mm5RLkFzl1WGyQytonWVWaHOOzdBhfr');

  async function fetchData() {
    try {
      const resp = await client.photos.search({query: 'Nature', per_page: 12, page: count})
      setCount(count + 1)
      setResponse(resp.photos)
    } catch (e) {
      console.log(e)

    }

  }

  useEffect(() => {
    fetchData()
  }, []);
  console.log(response)

  return (
    <div>
      <h1 style={{display: "flex", justifyContent: "center"}}>Zdjęcia: </h1>
      <div className="buttonsContainer">
        <button onClick={() => setResponse([])}>Wyczyść zdjęcia</button>
        <button onClick={() => fetchData()}>Załaduj zdjęcia</button>
      </div>
      <div className="container">
        {response?.map(image => (<Image key={image.id} image={image}/>))}
      </div>
    </div>
  )
}

export default App

// angular/src/app/app.component.ts
import {Component, OnInit} from '@angular/core';
import {createClient} from 'pexels';
import {HttpClient} from "@angular/common/http";

@Component({
  selector: 'app-root',
  // standalone: true,
  // imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent implements OnInit {
  photos: any[] = [];
  currentPage = 1;

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.fetchData();
  }


  async fetchData() {
    const client = createClient('eqDK60Xl9lzIP4RHt4YCNdwO2mm5RLkFzl1WGyQytonWVWaHOOzdBhfr');
    const resp = await client.photos.search({query: 'Nature', per_page: 12, page: this.currentPage})
    this.currentPage++;
    console.log(this.photos)
    // @ts-ignore
    this.photos = resp.photos;
  }

  clearPhotos() {
    this.photos = [];
    this.currentPage = 1;
  }


}

<h1 class="header">Zdjęcia:</h1>
<div class="buttonsContainer">
  <button (click)="fetchData()">Załaduj dane</button>
  <button (click)="clearPhotos()">Wyczyść dane</button>
</div>
<div class="container">
  <div  *ngFor="let photo of photos">
    <photo [photo]="photo"></photo>
  </div>
</div>
